gui:
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - underline
  nerdFontsVersion: '3'
  showCommandLog: false
  skipDiscardChangeWarning: true
git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side
  disableForcePushing: true
refresher:
  refreshInterval: 3
os:
  open: 'nvim --server "$NVIM" --remote-send "<C-\><C-N>:execute \"lua Zenvim.toggle_lazygit()\" | e {{filename}}<CR>"'

