---
"editor_view:move_to_and_select_buffer_start": none
"editor_view:delete": none
"editor_view:end": none
"workspace:activate_next_tab": meta-n
"editor_view:home": none
"pane_group:navigate_down": ctrl-alt-down
"pane_group:add_down": meta--
"pane_group:navigate_prev": meta-j
"pane_group:navigate_next": meta-l
"terminal:executing_command_move_cursor_word_left": none
"workspace:activate_prev_tab": meta-p
"editor_view:cut_word_left": none
"editor_view:move_forward_one_word": none
"workspace:shift_focus_left": none
"workspace:new_tab": ctrl-t
"pane_group:navigate_right": none
"editor_view:cmd_up": none
"editor_view:move_to_and_select_buffer_end": none
"pane_group:add_left": none
"pane_group:navigate_left": none
"workspace:toggle_command_palette": ctrl-shift-P
"editor_view:down": none
"pane_group:add_right": meta-d
"editor_view:add_next_occurrence": none
"pane_group:toggle_maximize_pane": meta-z
"editor_view:cmd_down": none
"editor_view:up": none
"terminal:executing_command_move_cursor_word_right": none
"workspace:shift_focus_right": none
"workspace:close_active_tab": ctrl-q
"editor_view:move_backward_one_word": none
