[helpers]

[default]
depends = []

[default.files]
"settings/zsh" = { target = "~/", type = "symbolic", recurse = true}
"settings/aqua" = { target = "~/.config/aquaproj-aqua", type = "symbolic" , recurse = false}
"settings/alacritty" = { target = "~/.config/alacritty", type = "symbolic", recurse = false}
"settings/zenvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false}
"settings/wezterm" = { target = "~/.config/wezterm", type = "symbolic", recurse = false}
".scripts" = { target = "~/.scripts", type = "symbolic", recurse = false}

[default.variables]

[settings]
default_target_type = "automatic"
